#!/bin/sh -e

TAG=$(git describe --abbrev=0 --tags)

packages=(
    "cw-agent"
    "database-proxy"
    "reports"
    "votes"
    "web"
#    "queue-proxy"
#    "worker"
#    "vote"
)

if [ $1 = "v2" ]; then
    tag="$TAG-2"
    img=subfuzion/vote-reports:$tag
    docker build --build-arg VERSION=$tag -t $img src/reports
    docker push $img
    exit
fi

i=0
total=${#packages[@]}
for pkg in ${packages[@]}; do
    ((i++))
    image=subfuzion/vote

    # naming 'vote' pkg => 'subfuzion/vote-vote' would be weird
    # it's the client, so just want "subfuzion/vote"
    if [ $pkg != "vote" ]; then
        image=$image-$pkg
    fi
    printf "\nBuilding image $i of $total: $image ...\n"
    docker build -t $image:latest src/$pkg

    docker tag $image $image:$TAG
    printf "Successfully tagged $image:$TAG\n"

    docker push $image:latest
    docker push $image:$TAG
done
