#!/bin/sh -e

TAG=$(git describe --abbrev=0 --tags)

packages=(
    "worker"
    "votes"
    "reports"
    "web"
    "vote"
)

for pkg in ${packages[@]}; do
    image=subfuzion/vote

    # naming 'vote' pkg => 'subfuzion/vote-vote' would be weird
    # it's the client, so just want "subfuzion/vote"
    if [ $pkg != "vote" ]; then
        image=$image-$pkg
    fi
    printf "\nBuild $image...\n"
    docker build -t $image src/$pkg

    docker tag $image $image:$TAG
    printf "Successfully tagged $image:$TAG"
    
    docker push $image
    docker push $image:$TAG
done
