---
Description: 'AWS App Mesh - Arugula App'

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "simpleapp"
    
  AppImage:
    Description: The image for the app. All service tasks use the same image.
    Type: String
    Default: "088845923532.dkr.ecr.us-west-2.amazonaws.com/simplewebapp:latest"

  XdsEndpoint:
    Type: String
    Description: App Mesh resource (X) discovery XdsEndpoint
    Default: "envoy-management.us-west-2.gamma.lattice.aws.a2z.com:443"

  SideCarRouterManagerImage:
    Type: String
    Description: Sidecar router manager that sets up networking for transparent proxy
    Default: "111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager"

  EnvoyImage:
    Type: String
    Description: Envoy image to use
    Default: "111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy"

  ServiceLogGroupRetentionInDays:
    Type: Number
    Default: 90

  ServicesDomain:
    Type: String
    Default: simpleapp.local

  EnvoyLogLevel:
    Type: String
    Default: debug

  LatticeEgressIngoredIpCsv:
    Type: String
    Default: 169.254.170.2

  ServiceAv1ServiceEndpointIdentifier:
    Type: String
    Description: Lattice service A v1 endpoint identifier.

  ServiceBv1ServiceEndpointIdentifier:
    Type: String
    Description: Lattice service B v1 endpoint identifier.

  ServiceCv1ServiceEndpointIdentifier:
    Type: String
    Description: Lattice service C v1 endpoint identifier.

  ServiceDv1ServiceEndpointIdentifier:
    Type: String
    Description: Lattice service D v1 endpoint identifier.

Resources:
  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Security group for the service"
      VpcId: {'Fn::ImportValue': VPC}
      SecurityGroupIngress:
        - CidrIp: {'Fn::ImportValue': VpcCIDR}
          IpProtocol: -1

  TaskIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

  TaskExecutionIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  ServiceLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays:
        Ref: ServiceLogGroupRetentionInDays

  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Vpc:
        Fn::ImportValue: VPC
      Name: { Ref: ServicesDomain }

  ServiceAServiceDiscoveryRecord:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: "serviceA" 
      DnsConfig:
        NamespaceId: { Ref: ServiceDiscoveryNamespace }
        DnsRecords:
          - Type: A
            TTL: 300
      HealthCheckCustomConfig:
        FailureThreshold: 1

  ServiceBServiceDiscoveryRecord:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: "serviceB" 
      DnsConfig:
        NamespaceId: { Ref: ServiceDiscoveryNamespace }
        DnsRecords:
          - Type: A
            TTL: 300
      HealthCheckCustomConfig:
        FailureThreshold: 1      

  ServiceCServiceDiscoveryRecord:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: "serviceC" 
      DnsConfig:
        NamespaceId: { Ref: ServiceDiscoveryNamespace }
        DnsRecords:
          - Type: A
            TTL: 300
      HealthCheckCustomConfig:
        FailureThreshold: 1      

  ServiceDServiceDiscoveryRecord:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Name: "serviceD" 
      DnsConfig:
        NamespaceId: { Ref: ServiceDiscoveryNamespace }
        DnsRecords:
          - Type: A
            TTL: 300
      HealthCheckCustomConfig:
        FailureThreshold: 1      

  ServiceBService:
      Type: 'AWS::ECS::Service'
      Properties:
        Cluster:
          Ref: EnvironmentName
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 80
        DesiredCount: 1
        LaunchType: EC2
        ServiceRegistries:
          - RegistryArn:
              'Fn::GetAtt': ServiceBServiceDiscoveryRecord.Arn
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups:
              - Ref: ECSServiceSecurityGroup
            Subnets: 
              - {'Fn::ImportValue': PrivateSubnet1}
              - {'Fn::ImportValue': PrivateSubnet2}
        TaskDefinition: { Ref: ServiceBv1TaskDefinition } 
        
  ServiceBv1TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: "app"
          Image: !Ref AppImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceBv1-app"
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: "tcp"
          Environment:
            - Name: SERVICE_NAME
              Value: "serviceBv1"
        - Name: "envoy"
          Image: !Ref EnvoyImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceBv1-envoy"
          Environment:
            - Name: "APPMESH_XDS_ENDPOINT"
              Value: { Ref: XdsEndpoint }
            - Name: APPMESH_VIRTUAL_NODE_NAME
              Value: "serviceB.simpleapp.local"
            - Name: APPMESH_VIRTUAL_NODE_UID 
              Value: !Ref ServiceAv1ServiceEndpointIdentifier
            - Name: ENVOY_ADMIN_ACCESS_LOG_FILE
              Value: "/tmp/envoy_admin_access.log"
            - Name: ENVOY_CONFIG_FILE
              Value: "/tmp/envoy.yaml"

          User: "1337"
          VolumesFrom:
            - SourceContainer: "app"

        - Name: "proxyinit"
          Image: !Ref SideCarRouterManagerImage
          Essential: false
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceBv1-proxyinit"
          LinuxParameters:
            Capabilities:
              Add:
                - "NET_ADMIN"
          Environment:
            - Name: "APPMESH_START_ENABLED"
              Value: "1"
            - Name: "APPMESH_USE_TPROXY"
              Value: "0"
            - Name: "APPMESH_IGNORE_UID"
              Value: "1337"
            - Name: "APPMESH_ENVOY_INGRESS_PORT"
              Value: "15000"
            - Name: "APPMESH_ENVOY_EGRESS_PORT"
              Value: "15001"
            - Name: "APPMESH_APP_PORTS"
              Value: "8080"
            - Name: "APPMESH_EGRESS_IGNORED_IP"
              Value: { Ref: "LatticeEgressIngoredIpCsv" }
      ExecutionRoleArn: { "Fn::GetAtt": TaskExecutionIamRole.Arn }
      NetworkMode: "awsvpc"
      Memory: 256

  ServiceCService:
      Type: 'AWS::ECS::Service'
      Properties:
        Cluster:
          Ref: EnvironmentName
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 80
        DesiredCount: 1
        LaunchType: EC2
        ServiceRegistries:
          - RegistryArn:
              'Fn::GetAtt': ServiceCServiceDiscoveryRecord.Arn
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups:
              - Ref: ECSServiceSecurityGroup
            Subnets: 
              - {'Fn::ImportValue': PrivateSubnet1}
              - {'Fn::ImportValue': PrivateSubnet2}
        TaskDefinition: { Ref: ServiceCv1TaskDefinition } 
        
  ServiceCv1TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: "app"
          Image: !Ref AppImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceCv1-app"
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: "tcp"
          Environment:
            - Name: SERVICE_NAME
              Value: "serviceCv1"
        - Name: "envoy"
          Image: !Ref EnvoyImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceCv1-envoy"
          Environment:
            - Name: "APPMESH_XDS_ENDPOINT"
              Value: { Ref: XdsEndpoint }
            - Name: APPMESH_VIRTUAL_NODE_NAME
              Value: "serviceC.simpleapp.local"
            - Name: APPMESH_VIRTUAL_NODE_UID 
              Value: !Ref ServiceAv1ServiceEndpointIdentifier
            - Name: ENVOY_ADMIN_ACCESS_LOG_FILE
              Value: "/tmp/envoy_admin_access.log"
            - Name: ENVOY_CONFIG_FILE
              Value: "/tmp/envoy.yaml"

          User: "1337"
          VolumesFrom:
            - SourceContainer: "app"

        - Name: "proxyinit"
          Image: !Ref SideCarRouterManagerImage
          Essential: false
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceCv1-proxyinit"
          LinuxParameters:
            Capabilities:
              Add:
                - "NET_ADMIN"
          Environment:
            - Name: "APPMESH_START_ENABLED"
              Value: "1"
            - Name: "APPMESH_USE_TPROXY"
              Value: "0"
            - Name: "APPMESH_IGNORE_UID"
              Value: "1337"
            - Name: "APPMESH_ENVOY_INGRESS_PORT"
              Value: "15000"
            - Name: "APPMESH_ENVOY_EGRESS_PORT"
              Value: "15001"
            - Name: "APPMESH_APP_PORTS"
              Value: "8080"
            - Name: "APPMESH_EGRESS_IGNORED_IP"
              Value: { Ref: "LatticeEgressIngoredIpCsv" }
      ExecutionRoleArn: { "Fn::GetAtt": TaskExecutionIamRole.Arn }
      NetworkMode: "awsvpc"
      Memory: 256

  ServiceDService:
      Type: 'AWS::ECS::Service'
      Properties:
        Cluster:
          Ref: EnvironmentName
        DeploymentConfiguration:
          MaximumPercent: 200
          MinimumHealthyPercent: 80
        DesiredCount: 1
        LaunchType: EC2
        ServiceRegistries:
          - RegistryArn:
              'Fn::GetAtt': ServiceDServiceDiscoveryRecord.Arn
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups:
              - Ref: ECSServiceSecurityGroup
            Subnets: 
              - {'Fn::ImportValue': PrivateSubnet1}
              - {'Fn::ImportValue': PrivateSubnet2}
        TaskDefinition: { Ref: ServiceDv1TaskDefinition } 
        
  ServiceDv1TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: "app"
          Image: !Ref AppImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceDv1-app"
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: "tcp"
          Environment:
            - Name: SERVICE_NAME
              Value: "serviceDv1"
        - Name: "envoy"
          Image: !Ref EnvoyImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceDv1-envoy"
          Environment:
            - Name: "APPMESH_XDS_ENDPOINT"
              Value: { Ref: XdsEndpoint }
            - Name: APPMESH_VIRTUAL_NODE_NAME
              Value: "serviceD.simpleapp.local"
            - Name: APPMESH_VIRTUAL_NODE_UID 
              Value: !Ref ServiceAv1ServiceEndpointIdentifier
            - Name: ENVOY_ADMIN_ACCESS_LOG_FILE
              Value: "/tmp/envoy_admin_access.log"
            - Name: ENVOY_CONFIG_FILE
              Value: "/tmp/envoy.yaml"

          User: "1337"
          VolumesFrom:
            - SourceContainer: "app"

        - Name: "proxyinit"
          Image: !Ref SideCarRouterManagerImage
          Essential: false
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceDv1-proxyinit"
          LinuxParameters:
            Capabilities:
              Add:
                - "NET_ADMIN"
          Environment:
            - Name: "APPMESH_START_ENABLED"
              Value: "1"
            - Name: "APPMESH_USE_TPROXY"
              Value: "0"
            - Name: "APPMESH_IGNORE_UID"
              Value: "1337"
            - Name: "APPMESH_ENVOY_INGRESS_PORT"
              Value: "15000"
            - Name: "APPMESH_ENVOY_EGRESS_PORT"
              Value: "15001"
            - Name: "APPMESH_APP_PORTS"
              Value: "8080"
            - Name: "APPMESH_EGRESS_IGNORED_IP"
              Value: { Ref: "LatticeEgressIngoredIpCsv" }
      ExecutionRoleArn: { "Fn::GetAtt": TaskExecutionIamRole.Arn }
      NetworkMode: "awsvpc"
      Memory: 256

  ServiceAService:
    Type: 'AWS::ECS::Service'
    DependsOn: LoadBalancerRule
    Properties:
      Cluster:
        Ref: EnvironmentName
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 80
      DesiredCount: 1
      LaunchType: EC2
      ServiceRegistries:
        - RegistryArn:
            'Fn::GetAtt': ServiceAServiceDiscoveryRecord.Arn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Ref: ECSServiceSecurityGroup
          Subnets: 
            - {'Fn::ImportValue': PrivateSubnet1}
            - {'Fn::ImportValue': PrivateSubnet2}
      TaskDefinition: { Ref: ServiceAv1TaskDefinition } 
      LoadBalancers:
        - ContainerName: app
          ContainerPort: 8080
          TargetGroupArn: !Ref 'TargetGroup'

  ServiceAv1TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Name: "app"
          Image: !Ref AppImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceAv1-app"
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: "tcp"
          Environment:
            - Name: SERVICE_NAME
              Value: "serviceAv1"
            - Name: BACKENDS
              Value: '{ "backends": [ "serviceb.simpleapp.local:8080", "servicec.simpleapp.local:8080" ] }'
        - Name: "envoy"
          Image: !Ref EnvoyImage
          Essential: true
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceAv1-envoy"
          Environment:
            - Name: "APPMESH_XDS_ENDPOINT"
              Value: { Ref: XdsEndpoint }
            - Name: APPMESH_VIRTUAL_NODE_NAME
              Value: "serviceA.simpleapp.local"
            - Name: APPMESH_VIRTUAL_NODE_UID 
              Value: !Ref ServiceAv1ServiceEndpointIdentifier
            - Name: ENVOY_ADMIN_ACCESS_LOG_FILE
              Value: "/tmp/envoy_admin_access.log"
            - Name: ENVOY_CONFIG_FILE
              Value: "/tmp/envoy.yaml"

          User: "1337"
          VolumesFrom:
            - SourceContainer: "app"

        - Name: "proxyinit"
          Image: !Ref SideCarRouterManagerImage
          Essential: false
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: { Ref: ServiceLogGroup }
              awslogs-region: { Ref: "AWS::Region" }
              awslogs-stream-prefix: "serviceAv1-proxyinit"
          LinuxParameters:
            Capabilities:
              Add:
                - "NET_ADMIN"
          Environment:
            - Name: "APPMESH_START_ENABLED"
              Value: "1"
            - Name: "APPMESH_USE_TPROXY"
              Value: "0"
            - Name: "APPMESH_IGNORE_UID"
              Value: "1337"
            - Name: "APPMESH_ENVOY_INGRESS_PORT"
              Value: "15000"
            - Name: "APPMESH_ENVOY_EGRESS_PORT"
              Value: "15001"
            - Name: "APPMESH_APP_PORTS"
              Value: "8080"
            - Name: "APPMESH_EGRESS_IGNORED_IP"
              Value: { Ref: "LatticeEgressIngoredIpCsv" }
      ExecutionRoleArn: { "Fn::GetAtt": TaskExecutionIamRole.Arn }
      NetworkMode: "awsvpc"
      Memory: 256

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: ip
      Name: ServiceA
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
      VpcId: 
        Fn::ImportValue: VPC

  # Create a rule on the load balancer for routing traffic to the target group
  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
      Conditions:
        - Field: path-pattern
          Values: ["*"]
      ListenerArn:
        Fn::ImportValue: PublicListener
      Priority: 1